name: CI

on: [push]

jobs:
  build:
    name: Setup & run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: pip
          cache-dependency-path: server/requirements-dev.txt
      - name: Install dependencies
        run: python -m pip install -r server/requirements-dev.txt
      - name: Run tests
        run: cd server && python -m pytest
